@echo off
echo Limpando projeto Flutter...

echo 1. Removendo diretório .dart_tool...
if exist .dart_tool rmdir /s /q .dart_tool

echo 2. Removendo diretório build...
if exist build rmdir /s /q build

echo 3. Removendo diretório .flutter-plugins...
if exist .flutter-plugins del /f .flutter-plugins

echo 4. Removendo diretório .flutter-plugins-dependencies...
if exist .flutter-plugins-dependencies del /f .flutter-plugins-dependencies

echo 5. Removendo pubspec.lock...
if exist pubspec.lock del /f pubspec.lock

echo 6. Limpando cache do pub...
call flutter pub cache repair

echo 7. Obtendo dependências...
call flutter pub get

echo Limpeza concluída!