name: calma_ai_flutter
description: Aplicativo de bem-estar mental com meditações personalizadas e diário emocional inteligente.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  http: ^1.1.0
  shared_preferences: ^2.2.0
  audioplayers: ^5.2.0
  fl_chart: ^0.63.0
  onesignal_flutter: ^5.0.0
  
  # Firebase packages com versões compatíveis
  firebase_core: ^2.15.1
  firebase_auth: ^4.7.3
  # Removido firebase_auth_web temporariamente
  
  google_sign_in: ^6.1.4
  flutter_secure_storage: ^8.0.0
  intl: ^0.19.0
  flutter_local_notifications: ^16.3.0
  path_provider: ^2.1.2
  timezone: ^0.9.2
  
  # Manter js por enquanto
  js: ^0.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/background.jpg



