name: calma_ai_flutter
description: Aplicativo de bem-estar mental com meditações personalizadas e diário emocional inteligente.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  audioplayers: ^5.2.1
  fl_chart: ^0.68.0
  http: ^1.2.2
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  onesignal_flutter: ^5.2.2
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  flutter_local_notifications: ^16.3.0
  path_provider: ^2.1.2
  js: ^0.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/background.jpg
